package betoncomputers;


import java.awt.Color;
import javax.swing.JOptionPane;
import betoncomputers.MainMenu;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author M  E  S  K  O
 */
public class loginForm extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public loginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        desnolgn = new javax.swing.JPanel();
        levo = new javax.swing.JPanel();
        lgnPic = new javax.swing.JLabel();
        lgnHeader = new javax.swing.JLabel();
        lgnSlgn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userFld = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        pwFld = new javax.swing.JPasswordField();
        showPw = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Beton Computers");
        setForeground(java.awt.Color.darkGray);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        desnolgn.setBackground(new java.awt.Color(255, 255, 255));
        desnolgn.setForeground(new java.awt.Color(51, 51, 51));
        desnolgn.setPreferredSize(new java.awt.Dimension(800, 500));

        levo.setBackground(new java.awt.Color(0, 105, 105));
        levo.setPreferredSize(new java.awt.Dimension(400, 500));

        lgnPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/loginPic.png"))); // NOI18N

        lgnHeader.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        lgnHeader.setForeground(new java.awt.Color(255, 255, 255));
        lgnHeader.setText("BETON COMPUTERS");

        lgnSlgn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lgnSlgn.setForeground(new java.awt.Color(255, 255, 255));
        lgnSlgn.setText("Vaši zahtevi, naša briga.");

        javax.swing.GroupLayout levoLayout = new javax.swing.GroupLayout(levo);
        levo.setLayout(levoLayout);
        levoLayout.setHorizontalGroup(
            levoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(levoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lgnHeader)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, levoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(levoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lgnPic, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lgnSlgn))
                .addGap(82, 82, 82))
        );
        levoLayout.setVerticalGroup(
            levoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, levoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lgnHeader)
                .addGap(45, 45, 45)
                .addComponent(lgnSlgn)
                .addGap(26, 26, 26)
                .addComponent(lgnPic, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jLabel4.setBackground(new java.awt.Color(0, 105, 105));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 105, 105));
        jLabel4.setText("Prijavi se na profil");

        userFld.setForeground(new java.awt.Color(204, 204, 204));
        userFld.setText("Korisničko Ime");
        userFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userFldMouseClicked(evt);
            }
        });
        userFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userFldKeyPressed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(0, 105, 105));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("LOGIN");
        loginBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginBtn.setBorderPainted(false);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        pwFld.setText("                    ");
        pwFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwFldMouseClicked(evt);
            }
        });

        showPw.setText("Prikaži Lozinku");
        showPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPwActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout desnolgnLayout = new javax.swing.GroupLayout(desnolgn);
        desnolgn.setLayout(desnolgnLayout);
        desnolgnLayout.setHorizontalGroup(
            desnolgnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desnolgnLayout.createSequentialGroup()
                .addComponent(levo, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(desnolgnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desnolgnLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(desnolgnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desnolgnLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(userFld, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwFld, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(desnolgnLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desnolgnLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showPw, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );
        desnolgnLayout.setVerticalGroup(
            desnolgnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(levo, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(desnolgnLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(userFld, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(pwFld, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showPw)
                .addGap(52, 52, 52)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(652, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(desnolgn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(desnolgn, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(816, 478));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userFldMouseClicked
        userFld.setText("");
    }//GEN-LAST:event_userFldMouseClicked

    private void userFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userFldKeyPressed
        userFld.setForeground(Color.BLACK);
    }//GEN-LAST:event_userFldKeyPressed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String username, lozinka;
        String url = "jdbc:mysql://localhost:3306/betoncomputers";
        String user = "root";
        String password = "";

        username = userFld.getText();  // Unos korisničkog imena
        lozinka = pwFld.getText();  // Unos lozinke

        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Unesite Korisnicko Ime", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (lozinka.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Unesite Lozinku", "Greška", JOptionPane.ERROR_MESSAGE);
            return;

        }

        if (!username.equals(username.toLowerCase())) {
            JOptionPane.showMessageDialog(null, "Admin nije pronađen (koristite mala slova)", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (Connection con = DriverManager.getConnection(url, user, password)) {
            // Učitaj JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Korišćenje PreparedStatement radi sprečavanja SQL injekcija
            String query = "SELECT lozinka FROM admin WHERE username = ?";
            try (PreparedStatement pst = con.prepareStatement(query)) {
                pst.setString(1, username);

                // Izvrši upit
                try (ResultSet rs = pst.executeQuery()) {
                    if (rs.next()) {
                        // Ako korisnik postoji, izvuci lozinku iz baze
                        String lozinkaDb = rs.getString("lozinka");

                        // Proveri da li se lozinka iz baze podudara sa unetom lozinkom
                        if (lozinka.equals(lozinkaDb)) {
                            // Ako se podudaraju, prijavi korisnika
                            JOptionPane.showMessageDialog(null, "Uspešno ste prijavljeni!");

                            MainMenu c=new MainMenu();
                            c.setVisible(true);
                            c.pack();
                            c.setDefaultCloseOperation (loginForm.EXIT_ON_CLOSE);

                            this.dispose();
                        }

                        else {
                            // Ako lozinke nisu iste, prikaži grešku
                            JOptionPane.showMessageDialog(null, "Pogrešna lozinka", "Greška", JOptionPane.ERROR_MESSAGE);
                        }

                    } else {
                        // Ako korisnik nije pronađen, prikaži grešku
                        JOptionPane.showMessageDialog(null, "Admin nije pronađen", "Greška", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "SQL greška: " + e.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Driver nije pronađen: " + e.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void pwFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwFldMouseClicked
        pwFld.setText("");
    }//GEN-LAST:event_pwFldMouseClicked

    private void showPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPwActionPerformed
        if (showPw.isSelected()) {
            pwFld.setEchoChar((char) 0);
        } else {
            pwFld.setEchoChar('*');
        }
    }//GEN-LAST:event_showPwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel desnolgn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel levo;
    private javax.swing.JLabel lgnHeader;
    private javax.swing.JLabel lgnPic;
    private javax.swing.JLabel lgnSlgn;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField pwFld;
    private javax.swing.JCheckBox showPw;
    private javax.swing.JTextField userFld;
    // End of variables declaration//GEN-END:variables
}
